language: php
php:
- 7.1.9
before_script:
- composer self-update
- composer install --prefer-source --no-interaction --dev
script:
- echo "skipping tests"
before_install:
  - rvm install 2.2.2
  - openssl aes-256-cbc -K $encrypted_b0b2958c016f_key -iv $encrypted_b0b2958c016f_iv -in .travis/travis_rsa.enc -out ~/.ssh/travis_rsa -d
  - chmod 600 ~/.ssh/travis_rsa
install:
- composer install
notifications:
  email: wmdmalinda@gmail.com
addons:
  ssh_known_hosts: 159.203.175.102
branches:
  only:
  - master
deploy:
  skip-cleanup: true
  provider: script
  script: ".travis/deploy.sh"
  on:
    branch: master
