language: php
php:
 -  7.1.9

before_script:
 - composer self-update
 - composer install --prefer-source --no-interaction --dev

script: phpunit

before-install:
 - composer self-update

install:
 - composer install

notifications:
 email: wmdmalinda@gmail.com