language: php
php:
- 7.1.9
before_script:
- composer self-update
- composer install --prefer-source --no-interaction --dev
script:
- echo "skipping tests"
before_install:
- rvm install 2.2.2
- openssl aes-256-cbc -K $encrypted_f9e1061e29ad_key -iv $encrypted_f9e1061e29ad_iv -in travis_rsa.enc -out ./.travis/travis_rsa -d
# - chmod 600 .travis/travis_rsa
install:
- composer install
addons:
  ssh_known_hosts: 165.22.48.48
branches:
  only:
  - master
deploy:
  skip-cleanup: true
  provider: script
  script: 
    - set -xe
    - echo "Running add config.user"
    - git config user.name "Ommz94"
    - echo "Running add config.email"
    - git config user.email "omeashgaya1@gmail.com"
    - echo "Running pull"
    - git pull origin master
  on:
    branch: master
